apiVersion: v1
kind: Service
metadata:
    name: polder-federated-search-service
spec:
   selector:
      app: polder-federated-search
   ports:
   - protocol: "TCP"
     port: 5000
     nodePort: 30001
     targetPort: 5000
   type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: polder-federated-search-deployment
  labels:
    app: polder-federated-search
spec:
  selector:
    matchLabels:
      app: polder-federated-search
  template:
    metadata:
      labels:
        app: polder-federated-search
    spec:
      volumes:
      - name: triplestore-volume
        emptyDir: {} # TODO: persistent storage would be nicer.
      - name: s3system-volume
        emptyDir: {}
      containers:
      - name: triplestore
        image: nawer/blazegraph
        volumeMounts:
        - mountPath: /var/lib/blazegraph
          name: triplestore-volume
        ports:
        - containerPort: 9999
        env:
        - name: JAVA_XMS
          value: 2g
        - name: JAVA_XMX
          value: 8g
        - name: JAVA_OPTS
          value: -Xmx6g -Xms2g --XX:+UseG1GC
      - name: s3system
        image: minio/minio:latest
        volumeMounts:
        - mountPath: /data
          name: s3system-volume
        ports:
          - containerPort: 54321
          - containerPort: 9000
        env:
          - name: MINIO_ACCESS_KEY
          - name: MINIO_SECRET_KEY
        command: ["server"]
        args: ["/data", "--console-address", ":54321"]
      - name: headless
        image: chromedp/headless-shell:latest
        ports:
          - containerPort: 9222
        env:
          - name: SERVICE_PORTS
            value: "9222"
      - name: webapp
        image: nein09/polder-federated-search:latest
        ports:
          - containerPort: 5000
        env:
          - name: GLEANER_ENDPOINT_URL
            value: http://triplestore:9999/blazegraph/namespace/polder/sparql
          - name: FLASK_APP
          - name: FLASK_RUN_HOST
          - name: SECRET_KEY
          - name: FLASK_ENV
