  authors_added[m
  caching-original_dataone_sources[m
  ci_build[m
  data_source_added[m
  escape_quote_bug[m
  fixing-datepicker[m
  fixing_duplicate_queries_gleaner[m
  gcmd_aboutme[m
  gem_doi[m
  gleaner_datasource[m
  indexing_gcmd[m
  kpi_dashboard[m
  license_addition[m
  license_bug[m
* [32mlucene_wildcards[m
  main[m
  new_ga_id[m
  new_location_added[m
  remove_buttons_nojs[m
  search_author_name[m
  show_more_button[m
  skip_link_for_screenreader[m
  zero_results[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/authors_added[m
  [31mremotes/origin/bas-investigation[m
  [31mremotes/origin/caching-original_dataone_sources[m
  [31mremotes/origin/center-loader-wheel-on-mobile[m
  [31mremotes/origin/data_source_added[m
  [31mremotes/origin/deploy-on-new-laptop[m
  [31mremotes/origin/enable-nsidc[m
  [31mremotes/origin/escape_quote_bug[m
  [31mremotes/origin/faceted-indexing[m
  [31mremotes/origin/fixing_duplicate_queries_gleaner[m
  [31mremotes/origin/gcmd_aboutme[m
  [31mremotes/origin/gem_doi[m
  [31mremotes/origin/graphdb[m
  [31mremotes/origin/indexing_gcmd[m
  [31mremotes/origin/kpi_dashboard[m
  [31mremotes/origin/license_addition[m
  [31mremotes/origin/license_bug[m
  [31mremotes/origin/location_added[m
  [31mremotes/origin/main[m
  [31mremotes/origin/map[m
  [31mremotes/origin/map-touchups[m
  [31mremotes/origin/nabu[m
  [31mremotes/origin/new_ga_id[m
  [31mremotes/origin/new_location_added[m
  [31mremotes/origin/nsidc-test[m
  [31mremotes/origin/remove_buttons_nojs[m
  [31mremotes/origin/search_author_name[m
  [31mremotes/origin/show_more_button[m
  [31mremotes/origin/skip_link_for_screenreader[m
