apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawl
spec:
  schedule: {{ .Values.crawlSchedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: crawl
        spec:
          restartPolicy: Never
          volumes:
          # todo: this is a shared config file with the initial index,
          # and it does a full index. Maybe just do a partial one?
          - name: gleaner-config
            configMap:
              name: gleaner-config
          - name: gleaner-context
            emptyDir: {}
          dnsPolicy: None
          dnsConfig:
            nameservers:
              - 10.96.0.10
            searches:
            - {{ .Release.Namespace }}.svc.cluster.local
            - svc.cluster.local
            - cluster.local
            options:
            - name: ndots
              value: "5"
          initContainers: # shared container specs
          # We need the latest schema.org context, so fetch it
          - name: get-contextfiles
            image: curlimages/curl:7.88.1
            command:
            - curl
            - -O
            - https://schema.org/version/latest/schemaorg-current-https.jsonld
            volumeMounts:
            - name: gleaner-context
              mountPath: /context
            workingDir: /context
          # Finally, index our data repositories!
          {{ include "gleaner-index" . | indent 10 }}
          containers:
          {{ include "write-to-triplestore" . | indent 10 }}
