apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawl
spec:
  schedule: "0 0 * * 3"
  jobTemplate:
    spec:
      template:
        metadata:
          name: crawl
        spec:
          restartPolicy: Never
          volumes:
          # todo: this is a shared config file with the initial index,
          # and it does a full index. Maybe just do a partial one?
          - name: gleaner-config
            configMap:
              name: gleaner-config
          - name: gleaner-context
            emptyDir: {}
          dnsPolicy: None
          dnsConfig:
            nameservers:
              - 10.96.0.10
            searches:
            - {{ .Release.Namespace }}.svc.cluster.local
            - svc.cluster.local
            - cluster.local
            options:
            - name: ndots
              value: "5"
          initContainers:
          - name: get-contextfiles
            image: curlimages/curl:7.82.0
            command:
            - curl
            - -O
            - https://schema.org/version/latest/schemaorg-current-https.jsonld
            volumeMounts:
            - name: gleaner-context
              mountPath: /context
            workingDir: /context
          - name: gleaner-index
            image:nsfearthcube/gleaner:dev-v3.0.4-development
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
            - -cfg
            - gleaner
            env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key:  minioAccessKey
                  name: {{ .Release.Name }}-secrets
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key:  minioSecretKey
                  name: {{ .Release.Name }}-secrets
            workingDir: /config
            volumeMounts:
            - name: gleaner-config
              mountPath: /config/gleaner.yaml
              subPath: gleaner.yaml
            - name: gleaner-context
              mountPath: /config
          containers:
          - name: write-to-triplestore
            image: bitnami/minio-client:2022
            env:
            - name: MINIO_CLIENT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key:  minioAccessKey
                  name: {{ .Release.Name }}-secrets
            - name: MINIO_CLIENT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key:  minioSecretKey
                  name: {{ .Release.Name }}-secrets
            - name: MINIO_SERVER_HOST
              value: {{ include "gleaner.s3system.endpoint" . }}
            - name: MINIO_SERVER_PORT_NUMBER
              value: "{{ .Values.s3system_service.api_port }}"
            command:
            # the first line of the following bash command is supposed to happen automatically, according to
            # the documentation on docker hub, but it does not.
            - /bin/bash
            - -c
            - >
              mc config host add minio "http://${MINIO_SERVER_HOST}:${MINIO_SERVER_PORT_NUMBER}" "${MINIO_CLIENT_ACCESS_KEY}" "${MINIO_CLIENT_SECRET_KEY}" &&
              for i in $(mc find minio/{{ .Values.storageNamespace }}/milled); do
                mc cat $i | curl -X POST -H 'Content-Type:text/rdf+n3' --data-binary  @- {{ include "gleaner.triplestore.endpoint" . }}namespace/{{ .Values.storageNamespace }}/sparql
              done
