{{ if eq .Values.dataLocation "dev" }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev-volume-triplestore
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: ceph-rbd
  volumeName: polder-pvc-01
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev-volume-s3system
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: ceph-rbd
  volumeName: polder-pvc-01
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
{{ end }}
