apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gleaner.fullname" . }}
  labels:
    {{- include "gleaner.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gleaner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gleaner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: triplestore-volume
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existing }}polder-pvc-01{{ else }}local-volume-triplestore{{ end }}
          readOnly: false
      - name: s3system-volume
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existing }}polder-pvc-02{{ else }}local-volume-s3system{{ end }}
          readOnly: false
      - name: triplestore-config
        configMap:
          name: triplestore-config
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.96.0.10
        searches:
        - {{ .Release.Namespace }}.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        options:
        - name: ndots
          value: "5"
      initContainers:
      # You can't just mount a configMap for the graphdb users and settings
      # because configMaps are read-only, so you have to mount one
      # here and copy it into the volume.
      # see https://github.com/Ontotext-AD/graphdb-helm/blob/master/templates/graphdb-node.yaml
      - name: provision-settings
        image: busybox:1
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /opt/graphdb/home
          name: triplestore-volume
        - mountPath: /tmp/graphdb-settings
          name: triplestore-config
        command: ['sh', '-c']
        args:
            - |
              set -eu
              if [[ -f /tmp/graphdb-settings/users.js ]]; then
                echo "Provisioning users with users.js file..."
                mkdir -p /opt/graphdb/home/data ;
                cp /tmp/graphdb-settings/users.js /opt/graphdb/home/data/users.js
              fi
              if [[ -f /tmp/graphdb-settings/settings.js ]]; then
                echo "Provisioning settings with settings.js file..."
                mkdir -p /opt/graphdb/home/data ;
                cp /tmp/graphdb-settings/settings.js /opt/graphdb/home/data/settings.js
              fi
              echo 'Done'
      containers:
      - name: triplestore
        image: ontotext/graphdb:10.2.0
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /opt/graphdb/home
          name: triplestore-volume

        ports:
        - containerPort: {{ .Values.triplestore_service.port }}
        env:
        - name: GDB_JAVA_OPTS
          value: {{ .Values.GDB_JAVA_OPTS }}
      - name: s3system
        image: minio/minio:RELEASE.2022-10-24T18-35-07Z
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /data
          name: s3system-volume
        command:
        - minio
        - server
        - /data
        ports:
        - containerPort: {{ .Values.s3system_service.ui_port }}
        - containerPort: {{ .Values.s3system_service.api_port }}
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              key:  minioAccessKey
              name: {{ .Release.Name }}-secrets
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key:  minioSecretKey
              name: {{ .Release.Name }}-secrets
        - name: MINIO_API_TRANSITION_WORKERS
          value: "{{ .Values.MINIO_WORKERS }}"
      - name: headless
        image: chromedp/headless-shell::104.0.5098.0
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.headless_service.port }}
        env:
        - name: SERVICE_PORTS
          value: "{{ .Values.headless_service.port }}"
        args: --disable-gpu
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
