apiVersion: v1
kind: ConfigMap
metadata:
  name: gleaner-config
  labels:
    app: gleaner
data:
  gleaner.yaml: |-
    minio:
      address: {{ .Values.s3system_service.ip_address }}
      port: {{ .Values.s3system_service.api_port }}
      ssl: false
      bucket: {{ .Values.storageNamespace }}
    gleaner:
      runid: {{ .Values.storageNamespace }}
      summon: true
      mill: true
    context:
      cache: true
    contextmaps:
    - prefix: "https://schema.org/"
      file: "./schemaorg-current-https.jsonld"
    - prefix: "http://schema.org/"
      file: "./schemaorg-current-https.jsonld"
    - prefix: "http://schema.org"
      file: "./schemaorg-current-https.jsonld"
    summoner:
      after: ""
      mode: full  # full || diff:  If diff compare what we have currently in gleaner to sitemap, get only new, delete missing
      threads: 5
      delay:  # milliseconds (1000 = 1 second) to delay between calls (will FORCE threads to 1)
      headless: http://headless-svc:{{ .Values.headless_service.port }}
    millers:
      graph: true
    sources:
    - name: nsidc
      url: https://nsidc.org/sitemap.xml
      headless: false
      properName: National Snow and Ice Data Center
      domain: https://nsidc.org
      type: sitemap
      active: false
    - name: gem
      type: sitemap
      headless: true
      url: https://data.g-e-m.dk/sitemap
      properName: Greenland Ecosystem Monitoring Database
      domain: https://data.g-e-m.dk
      active: true
    - name: bas
      type: sitemap
      headless: false
      url: http://s3system-svc:{{ .Values.s3system_service.api_port }}/sitemaps/bas-sitemap.xml
      properName: British Antarctic Survey
      active: true
      domain: http://bas.ac.uk
