apiVersion: v1
kind: ConfigMap
metadata:
  name: polder-repo-config
  labels:
    app: triplestore
data:
  geosparql.sparql: |-
{{ tpl (.Files.Get "files/graphdb/geosparql.sparql" | indent 4) . }}
  lucene-connector.sparql: |-
{{ tpl (.Files.Get "files/graphdb/lucene-connector.sparql" | indent 4) . }}
  polder.ttl: |-
{{ tpl (.Files.Get "files/graphdb/polder.ttl" | indent 4) . }}
  triplestore-setup.sh: |-
{{ tpl (.Files.Get "files/graphdb/triplestore-setup.sh" | indent 4) . }}
  write-to-triplestore.sh: |-
{{ tpl (.Files.Get "files/graphdb/write-to-triplestore.sh" | indent 4) . }}
  clear-triplestore.sh: |-
{{ tpl (.Files.Get "files/graphdb/clear-triplestore.sh" | indent 4) . }}
