apiVersion: batch/v1
kind: CronJob
metadata:
  name: recreate-index
spec:
  # 30th of February run, will never be run automatically, only when we trigger it
  # Yes, this is cursed, but this is the only way you can put a manual-only job in a Helm chart
  schedule: "0 0 30 2 0"
  jobTemplate:
    spec:
      template:
        metadata:
          name: recreate-index
        spec:
          restartPolicy: Never
          volumes:
          # todo: this is a shared config file with the initial index,
          # and it does a full index. Maybe just do a partial one?
          - name: gleaner-config
            configMap:
              name: gleaner-config
          - name: gleaner-context
            emptyDir: {}
          - name: polder-repo-config
            configMap:
              name: polder-repo-config
          initContainers:
          - name: remove-minio-files
            image: minio/mc:RELEASE.2022-11-17T21-20-39Z
            env:
            - name: MINIO_CLIENT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key:  minioAccessKey
                  name: {{ .Release.Name }}-secrets
            - name: MINIO_CLIENT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key:  minioSecretKey
                  name: {{ .Release.Name }}-secrets
            - name: MINIO_SERVER_HOST
              value: {{ include "gleaner.s3system.endpoint" . }}
            - name: MINIO_SERVER_PORT_NUMBER
              value: "{{ .Values.s3system_service.api_port }}"
            command:
            # the first line of the following bash command is supposed to happen automatically, according to
            # the documentation on docker hub, but it does not.
            - /bin/bash
            - -c
            - >
              mc config host add minio "http://${MINIO_SERVER_HOST}:${MINIO_SERVER_PORT_NUMBER}" "${MINIO_CLIENT_ACCESS_KEY}" "${MINIO_CLIENT_SECRET_KEY}" &&
              mc rm -r --force minio/{{ .Values.storageNamespace }}
          - name: get-contextfiles
            image: curlimages/curl:7.88.1
            command:
            - curl
            - -O
            - https://schema.org/version/latest/schemaorg-current-https.jsonld
            volumeMounts:
            - name: gleaner-context
              mountPath: /context
            workingDir: /context
          # Finally, index our data repositories!
          - {{ include "gleaner-index" . | indent 12 }}
          # The easiest way is just to remove the repository and recreate it
          - name: clear-triplestore
            image: curlimages/curl:7.88.1
            workingDir: /config
            volumeMounts:
            - name: polder-repo-config
              mountPath: /config
            env:
            - name: GLEANER_ENDPOINT_URL
              value: {{ include "gleaner.triplestore.endpoint" . }}/repositories/{{ .Values.storageNamespace }}
            - name: GRAPHDB_REST_URL
              value: {{ include "gleaner.triplestore.endpoint" . }}/rest
            command:
            - sh
            - -c
            - ./clear-triplestore.sh
          containers:
          - {{ include "write-to-triplestore" . }}


