apiVersion: v1
kind: Service
metadata:
  name: s3system-svc
  labels:
    run: s3system-svc
spec:
  type: {{ .Values.s3system_service.type }}
  clusterIP: {{ .Values.s3system_service.ip_address }}
  ports:
    - port: {{ .Values.s3system_service.api_port }}
      targetPort: {{ .Values.s3system_service.api_port }}
      protocol: TCP
  selector:
    {{- include "gleaner.selectorLabels" . | nindent 4 }}
