apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
  minioAccessKey: d29ybGRzYmVzdGFjY2Vzc2tleQ==
  minioSecretKey: d29ybGRzYmVzdHNlY3JldGtleQ==
  flaskSecretKey: YXNkZmFzZGZhZHNhZmdoc2tsamFk
