apiVersion: batch/v1
kind: Job
metadata:
  name: setup-gleaner
spec:
  template:
    metadata:
      name: setup-gleaner
    spec:
      restartPolicy: Never
      volumes:
      - name: gleaner-config
        configMap:
          name: gleaner-config
          items:
          - key: gleaner.yaml
            path: gleaner.yaml
      initContainers:
      - name: wait-for-triplestore-up
        image: curlimages/curl
        command:
        - /bin/sh
        - -c
        # yes, this is how it has to work, no I am not happy about it
        - >
          set -x;
          while [ $(curl -sw '%{http_code}' "{{ include "gleaner.triplestore.endpoint" . }}" -o /dev/null) -ne 200 ]; do
            sleep 15;
          done
      - name: setup-triplestore
        image: curlimages/curl
        command:
        - curl
        - -X
        - POST
        - -H
        - 'Content-type: application/xml'
        - --data
        - >
          <?xml version="1.0" encoding="UTF-8" standalone="no" ?>
            <!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
            <properties>
              <entry key="com.bigdata.rdf.store.AbstractTripleStore.textIndex">true</entry>
              <entry key="com.bigdata.rdf.store.AbstractTripleStore.axiomsClass">com.bigdata.rdf.axioms.NoAxioms</entry>
              <entry key="com.bigdata.rdf.sail.isolatableIndices">false</entry>
              <entry key="com.bigdata.rdf.sail.truthMaintenance">false</entry>
              <entry key="com.bigdata.rdf.store.AbstractTripleStore.justify">false</entry>
              <entry key="com.bigdata.rdf.sail.namespace">polder</entry>
              <entry key="com.bigdata.rdf.store.AbstractTripleStore.quads">true</entry>
              <entry key="com.bigdata.namespace.polder.spo.com.bigdata.btree.BTree.branchingFactor">1024</entry>
              <entry key="com.bigdata.journal.Journal.groupCommit">false</entry>
              <entry key="com.bigdata.namespace.polder.lex.com.bigdata.btree.BTree.branchingFactor">400</entry>
              <entry key="com.bigdata.rdf.store.AbstractTripleStore.geoSpatial">true</entry>
              <entry key="com.bigdata.rdf.store.AbstractTripleStore.statementIdentifiers">false</entry>
            </properties>
        - '{{- include "gleaner.triplestore.endpoint" . }}namespace'
      containers:
      - name: gleaner-setup
        image: fils/gleaner
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - -cfg
        - gleaner
        - -setup
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key:  minioAccessKey
              name: {{ .Release.Name }}-secrets
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key:  minioSecretKey
              name: {{ .Release.Name }}-secrets
        workingDir: /config
        volumeMounts:
        - name: gleaner-config
          mountPath: /config/gleaner.yaml
          subPath: gleaner.yaml
