apiVersion: batch/v1
kind: Job
metadata:
  name: setup-gleaner
spec:
  ttlSecondsAfterFinished: 10000
  template:
    metadata:
      name: setup-gleaner
    spec:
      restartPolicy: Never
      volumes:
      - name: gleaner-config
        configMap:
          name: gleaner-config
      {{ include "polder-repo-config-volume" . | indent 6 }}
      - name: gleaner-context
        emptyDir: {}
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.96.0.10
        searches:
        - {{ .Release.Namespace }}.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        options:
        - name: ndots
          value: "5"
      initContainers:
      # Create the graphdb repository that we want to use for this app
      - name: setup-triplestore
        image: curlimages/curl:7.88.1
        workingDir: /config
        volumeMounts:
        - name: polder-repo-config
          mountPath: /config
        command:
        - /bin/sh
        - ./triplestore-setup.sh
        env:
        - name: GLEANER_ENDPOINT_URL
          value: {{ include "gleaner.triplestore.endpoint" . }}/repositories/{{ .Values.storageNamespace }}
        - name: GRAPHDB_REST_URL
          value: {{ include "gleaner.triplestore.endpoint" . }}/rest
        - name: GRAPHDB_INDEXER_USER
          value: indexer-user
        - name: GRAPHDB_INDEXER_PASSWORD
          valueFrom:
            secretKeyRef:
              key:  graphdbIndexerPassword
              name: {{ .Release.Name }}-secrets
        - name: GRAPHDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key:  graphdbRootPassword
              name: {{ .Release.Name }}-secrets
      # Run gleaner setup, which creates cloud storage buckets
      - name: gleaner-setup
        image: nsfearthcube/gleaner:v3.0.8
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - -cfg
        - gleaner
        - -setup
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key:  minioAccessKey
              name: {{ .Release.Name }}-secrets
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key:  minioSecretKey
              name: {{ .Release.Name }}-secrets
        workingDir: /config
        volumeMounts:
        - name: gleaner-config
          mountPath: /config/gleaner.yaml
          subPath: gleaner.yaml
      - name: get-contextfiles
        image: curlimages/curl:7.88.1
        command:
        - curl
        - -O
        - https://schema.org/version/latest/schemaorg-current-https.jsonld
        volumeMounts:
        - name: gleaner-context
          mountPath: /context
        workingDir: /context
      # Dynamically create the sitemaps for BAS, GCMD and Datastream, and put
      # them somewhere that Gleaner can use to crawl
      - name: build-sitemap
        image: wdsito/build-sitemap:{{ .Values.image.tag | default .Chart.AppVersion }}
        env:
        - name: MINIO_CLIENT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key:  minioAccessKey
              name: {{ .Release.Name }}-secrets
        - name: MINIO_CLIENT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key:  minioSecretKey
              name: {{ .Release.Name }}-secrets
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              key:  minioAccessKey
              name: {{ .Release.Name }}-secrets
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key:  minioSecretKey
              name: {{ .Release.Name }}-secrets
        - name: MINIO_SERVER_HOST
          value: {{ include "gleaner.s3system.endpoint" . }}
        - name: MINIO_SERVER_PORT_NUMBER
          value: "{{ .Values.s3system_service.api_port }}"
        volumeMounts:
        - name: gleaner-context
          mountPath: /context
        workingDir: /context
      # Finally, index our data repositories!
      {{ include "gleaner-index" . | indent 6 }}
      containers:
      {{ include "write-to-triplestore" . | indent 6 }}

