apiVersion: v1
kind: Service
metadata:
  name: triplestore-svc
  labels:
    run: triplestore-svc
spec:
  type: NodePort
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 30001
      protocol: TCP
  selector:
    {{- include "gleaner.selectorLabels" . | nindent 4 }}
