services:

  gleaner-setup:
    image: fils/gleaner
    command: -cfg gleaner -setup
    depends_on:
      - triplestore
      - s3system
      - headless
    profiles:
      - setup
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    volumes:
      - ./:/config
    working_dir: /config

  gleaner:
    image: fils/gleaner
    # This should be a cron job or something
    command: -cfg gleaner
    depends_on:
      - triplestore
      - s3system
      - headless
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    profiles:
      - crawl
    volumes:
      - ./:/config
    working_dir: /config

# Todo: add nabu into the mix

  triplestore:
    image: nawer/blazegraph
    environment:
      JAVA_XMS: 2g
      JAVA_XMX: 8g
      JAVA_OPTS: -Xmx6g -Xms2g --XX:+UseG1GC
    ports:
      - 9999:9999
    volumes:
      - ${GLEANER_GRAPH}:/var/lib/blazegraph

  s3system:
    image: minio/minio:latest
    ports:
      - 54321:54321
      - 9000:9000
    volumes:
      - ${GLEANER_OBJECTS}:/data
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY"}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY"}
    command: ["server", "/data", "--console-address", ":54321"]

  headless:
    image: chromedp/headless-shell:latest
    ports:
      - 9222:9222
    environment:
     - SERVICE_PORTS=9222

  webapp:
    image: nein09/polder-federated-search:latest
    depends_on:
      - triplestore
      - s3system
    profiles:
      - web
    ports:
      - 5000:5000
    environment:
      # Overrides the environment variable so that we get the service endpoint IP from Docker.
      - GLEANER_ENDPOINT_URL=http://triplestore:9999/blazegraph/namespace/polder/sparql
      - FLASK_APP
      - FLASK_RUN_HOST
      - SECRET_KEY
      - FLASK_ENV
