volumes:
  s3system:
  triplestore:

services:

  gleaner-setup:
    image: nsfearthcube/gleaner:dev-v3.0.4-development
    command: -cfg gleaner -setup
    depends_on:
      - triplestore
      - s3system
      - headless
    profiles:
      - setup
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    volumes:
      - ./:/config
    working_dir: /config

  gleaner:
    image: nsfearthcube/gleaner:dev-v3.0.4-development
    command: -cfg gleaner
    depends_on:
      - triplestore
      - s3system
      - headless
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    profiles:
      - crawl
    volumes:
      - ./:/config
    working_dir: /config

  triplestore:
    image: nein09/fuseki-geosparql-lucene:0.1
    ports:
      - 9999:3030


  s3system:
    image: minio/minio
    ports:
      - 54321:54321
      - 9000:9000
    volumes:
      - s3system:/data
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: ["server", "/data", "--console-address", ":54321"]

  headless:
    image: chromedp/headless-shell:stable
    ports:
      - 9222:9222
    environment:
     - SERVICE_PORTS=9222

  webapp:
    image: nein09/polder-federated-search:1.41.0
    depends_on:
      - triplestore
      - s3system
    profiles:
      - web
    ports:
      # Change 8096 to 80 if you want to put this on a web server in production.
      - 8096:8000
    environment:
      # Overrides the environment variable so that we get the service endpoint IP from Docker.
      - GLEANER_ENDPOINT_URL=http://triplestore:8080/bigdata/namespace/polder/sparql
      - FLASK_APP
      - FLASK_RUN_HOST
      - SECRET_KEY
      - FLASK_ENV
      - SENTRY_DSN
      - SENTRY_ENVIRONMENT
      # These are both for running in a subdirectory. IF you don't want to do that,
      # you can delete the next two lines.
      # - SERVER_NAME=None
      # - SCRIPT_NAME=/polder
