volumes:
  s3system:
  triplestore:

services:

  gleaner-setup:
    image: fils/gleaner:v3.0.3-developement
    command: -cfg gleaner -setup
    depends_on:
      - triplestore
      - s3system
      - headless
    profiles:
      - setup
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    volumes:
      - ./:/config
    working_dir: /config

  triplestore-setup:
    image: curlimages/curl:7.80.0
    depends_on:
    - triplestore
    command:
    - curl
    - -X
    - POST
    - -H
    - 'Content-type: application/xml'
    - --data
    - >
      <?xml version="1.0" encoding="UTF-8" standalone="no" ?>
        <!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
        <properties>
          <entry key="com.bigdata.rdf.store.AbstractTripleStore.textIndex">true</entry>
          <entry key="com.bigdata.rdf.store.AbstractTripleStore.axiomsClass">com.bigdata.rdf.axioms.NoAxioms</entry>
          <entry key="com.bigdata.rdf.sail.isolatableIndices">false</entry>
          <entry key="com.bigdata.rdf.sail.truthMaintenance">false</entry>
          <entry key="com.bigdata.rdf.store.AbstractTripleStore.justify">false</entry>
          <entry key="com.bigdata.rdf.sail.namespace">polder</entry>
          <entry key="com.bigdata.rdf.store.AbstractTripleStore.quads">true</entry>
          <entry key="com.bigdata.namespace.polder.spo.com.bigdata.btree.BTree.branchingFactor">1024</entry>
          <entry key="com.bigdata.journal.Journal.groupCommit">false</entry>
          <entry key="com.bigdata.namespace.polder.lex.com.bigdata.btree.BTree.branchingFactor">400</entry>
          <entry key="com.bigdata.rdf.store.AbstractTripleStore.geoSpatial">true</entry>
          <entry key="com.bigdata.rdf.store.AbstractTripleStore.statementIdentifiers">false</entry>
        </properties>
    - 'http://triplestore:9999/blazegraph/namespace'

  gleaner:
    image: fils/gleaner:v3.0.3-developement
    command: -cfg gleaner
    depends_on:
      - triplestore
      - s3system
      - headless
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    profiles:
      - crawl
    volumes:
      - ./:/config
    working_dir: /config

  triplestore:
    image: nawer/blazegraph
    environment:
      JAVA_XMS: 2g
      JAVA_XMX: 8g
      JAVA_OPTS: -Xmx6g -Xms2g --XX:+UseG1GC
    ports:
      - 9999:9999
    volumes:
      - triplestore:/var/lib/blazegraph

  s3system:
    image: minio/minio:latest
    ports:
      - 54321:54321
      - 9000:9000
    volumes:
      - s3system:/data
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: ["server", "/data", "--console-address", ":54321"]

  headless:
    image: chromedp/headless-shell:latest
    ports:
      - 9222:9222
    environment:
     - SERVICE_PORTS=9222

  webapp:
    image: nein09/polder-federated-search:1.33.2
    depends_on:
      - triplestore
      - s3system
    profiles:
      - web
    ports:
      # Change 8096 to 80 if you want to put this on a web server in production.
      - 8096:8000
    environment:
      # Overrides the environment variable so that we get the service endpoint IP from Docker.
      - GLEANER_ENDPOINT_URL=http://triplestore:9999/blazegraph/namespace/polder/sparql
      - FLASK_APP
      - FLASK_RUN_HOST
      - SECRET_KEY
      - FLASK_ENV
      # These are both for running in a subdirectory. IF you don't want to do that,
      # you can delete the next two lines.
      - SERVER_NAME=None
      - SCRIPT_NAME=/polder
