volumes:
  s3system:
  triplestore:

services:

  gleaner-setup:
    image: nsfearthcube/gleaner:v3.0.8_fix129
    command: -cfg gleaner -setup
    depends_on:
      - triplestore
      - s3system
      - headless
    profiles:
      - setup
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    volumes:
      - ../deployment-support/gleaner/:/config
    working_dir: /config

  get-contextfiles:
    image: curlimages/curl:7.88.1
    profiles:
      - setup
    volumes:
      - ../deployment-support/gleaner/:/config
    working_dir: /config
    command: curl -O https://schema.org/version/latest/schemaorg-current-https.jsonld

  triplestore-setup:
    image: curlimages/curl:7.88.1
    depends_on:
    - triplestore
    volumes:
      - ../deployment-support/graphdb/:/config
    working_dir: /config
    environment:
      - GLEANER_ENDPOINT_URL=http://triplestore:7200/repositories/polder
      - GRAPHDB_REST_URL=http://triplestore:7200/rest
      - GRAPHDB_INDEXER_USER
      - GRAPHDB_INDEXER_PASSWORD
    command: sh ./triplestore-setup.sh

  sitemap-setup:
    image: wdsito/build-sitemap:1.46.0
    depends_on:
    - s3system
    profiles:
      - setup
    environment:
      - MINIO_CLIENT_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_CLIENT_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_SERVER_HOST=s3system
      - MINIO_SERVER_PORT_NUMBER=9000
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}

  gleaner:
    image: nsfearthcube/gleaner:v3.0.8_fix129
    command: -cfg docker
    depends_on:
      - triplestore
      - s3system
      - headless
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    profiles:
      - crawl
    volumes:
      - ../deployment-support/gleaner/:/config
    working_dir: /config

  triplestore:
    image: ontotext/graphdb:10.2.0
    volumes:
      - type: bind
        source: ../deployment-support/graphdb/graphdb-settings.js
        target: /opt/graphdb/home/data/settings.js
      - triplestore:/opt
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    ports:
      - 9999:7200

  s3system:
    image: minio/minio:RELEASE.2022-10-24T18-35-07Z
    ports:
      - 54321:54321
      - 9000:9000
    volumes:
      - s3system:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: ["server", "/data", "--console-address", ":54321"]

  headless:
    image: chromedp/headless-shell:stable
    ports:
      - 9222:9222
    environment:
     - SERVICE_PORTS=9222

  write-to-triplestore:
    image: minio/mc:RELEASE.2022-11-17T21-20-39Z
    depends_on:
      - triplestore
      - s3system
    volumes:
      - ../deployment-support/graphdb/:/config
    working_dir: /config
    environment:
      - GLEANER_ENDPOINT_URL=http://triplestore:7200/repositories/polder
      - GRAPHDB_REST_URL=http://triplestore:7200/rest
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - MINIO_SERVER_HOST=http://s3system
      - MINIO_SERVER_PORT=9000
      - GRAPHDB_INDEXER_USER
      - GRAPHDB_INDEXER_PASSWORD
    profiles:
      - write
    entrypoint: ["sh", "-c", "./write-to-triplestore.sh"]

  webapp:
    image: wdsito/polder-federated-search:1.46.0
    depends_on:
      - triplestore
      - s3system
    profiles:
      - web
    ports:
      # Change 8096 to 80 if you want to put this on a web server in production.
      - 8096:8000
    environment:
      # Overrides the environment variable so that we get the service endpoint IP from Docker.
      - GLEANER_ENDPOINT_URL=http://triplestore:7200/repositories/polder
      - FLASK_APP
      - FLASK_RUN_HOST
      - SECRET_KEY
      - FLASK_ENV
      - SENTRY_DSN
      - SENTRY_ENVIRONMENT
      # These are both for running in a subdirectory. IF you don't want to do that,
      # you can delete the next two lines.
      # - SERVER_NAME=None
      # - SCRIPT_NAME=/polder
