PREFIX con: <http://www.ontotext.com/connectors/lucene#>
PREFIX con-inst: <http://www.ontotext.com/connectors/lucene/instance#>

INSERT DATA {
    con-inst:full_text_search con:createConnector '''
    {
      "fields": [
        {
          "fieldName": "fts",
          "fieldNameTransform": "predicate.localName",
          "propertyChain": [
            "$literal"
          ],
          "facet": true
        },
        {
          "fieldName": "author",
          "propertyChain": [
            "https://schema.org/creator",
            "$literal"
          ],
          "facet": true
        },
        {
          "fieldName": "license$0",
          "propertyChain": [
            "https://schema.org/Dataset",
            "https://schema.org/license"
          ],
          "facet": true
        },
        {
          "fieldName": "license$1",
          "propertyChain": [
            "https://schema.org/Dataset",
            "https://schema.org/license",
            "https://schema.org/license"
          ],
          "facet": true
        },
        {
          "fieldName": "license$2",
          "propertyChain": [
            "https://schema.org/DataCatalog",
            "https://schema.org/license",
          ],
          "facet": true
        },
      ],
      "languages": [
        ""
      ],
      "types": [
        "$untyped"
      ]
    }
''' .
}
