minio:
  address: http://s3system-svc.{{ .Release.Namespace }}.svc.cluster.local:9000
  port: 9000   
  accessKey: worldsbestaccesskey # todo: put these in an environment variable
  secretKey: worldsbestsecretkey
  ssl: false
  bucket: gleaner
gleaner:
  runid: polder # Run ID used in prov and a few others
  summon: true # do we want to visit the web sites and pull down the files
  mill: true
context:
  cache: true
contextmaps:
- prefix: "https://schema.org/"
  file: "./schemaorg-current-https.jsonld"
- prefix: "http://schema.org/"
  file: "./schemaorg-current-https.jsonld"
- prefix: "http://schema.org"
  file: "./schemaorg-current-https.jsonld"
summoner:
  after: ""      # "21 May 20 10:00 UTC"   
  mode: full  # full || diff:  If diff compare what we have currently in gleaner to sitemap, get only new, delete missing
  threads: 5
  delay:  # milliseconds (1000 = 1 second) to delay between calls (will FORCE threads to 1) 
  headless: http://headless:9222  # URL for headless see docs/headless
millers:
  graph: true
sources:
- name: aadc
  url: https://data.aad.gov.au/metadata/sitemap.xml
  headless: false
  properName: Australian Antarctic Data Centre
  domain: https://data.aad.gov.au/
- name: nsidc
  url: https://nsidc.org/sitemap.xml
  headless: false
  properName: National Snow and Ice Data Center
  domain: https://nsidc.org
- name: adc
  url: https://arcticdata.io/sitemap_index.xml
  headless: true
  pid: https://www.re3data.org/repository/r3d100011973
  properName: Arctic Data Center
  domain: https://arcticdata.io
