# Local deployment values for polder-federated-search.

ingress:
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "36000"
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific

sentryEnvironment: local
googleAnalyticsId: UA-234464538-2

## Persist data to a persistent volume.
## Where are we storing the files we index and the triplestore data?
# Setting 'existing' to true means you're running on a cluster (probably DataONE's) that has a
## PersistentVolumeClaim. created for you.
persistence:
  existing: false

# A date in the past, will never run automatically, only when we trigger it
# Yes, this is cursed, but this is the only way you can put a manual-only job in a Helm chart
schedule: "0 0 0 1 1 ? 1970"
