# Dev deployment values for polder-federated-search.

ingress:
  hosts:
    - host: search-dev.polder.info
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - hosts:
    - search-dev.polder.info
    secretName: ingress-nginx-tls-cert

sentryEnvironment: development
googleAnalyticsId: UA-234464538-2

storageNamespace: polder

crawlSchedule: "0 0 * * 1" # every Monday
