# Production deployment values for polder-federated-search.

ingress:
  hosts:
    - host: search.polder.info
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - hosts:
    - search.polder.info
    secretName: ingress-nginx-tls-cert

# needs to be >= GOMAXPROCS/2. The default is 100.
# 100 just started failing as "too few" in production
# one day so here we are.
MINIO_WORKERS: 200

sentryEnvironment: production
googleAnalyticsId: G-6XZ31PHHSZ

crawlSchedule: "0 0 * * 3" # every Wednesday
