name: Build Docker Container
on:
   push:
    branches:
      - main
jobs:
  get-version-from-package-json-action:
    runs-on: ubuntu-latest
    name: Test get-version-from-package-json
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: get-version-from-package-json
        uses: polyseam/get-version-from-package-json@1.0.0
        id: get-version-from-package-json
        with:
          path-to-package-json: 'package.json'
      - name: print-version
        run: echo "The version key in your json is ${{steps.get-version-from-package-json.outputs.version}}"
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN}}
        - name: build docker container
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true 
            tags: wdsito/polder-federated-search:{{steps.get-version-from-package-json.outputs.version}}
        - name: build docker container
          id: sitemap_docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: wdsito/build-sitemaps:{{steps.get-version-from-package-json.outputs.version}}
            file: ./build-sitemap/Dockerfile
            context: .
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
        - name: Image digest
          run: echo ${{ steps.sitemap_docker_build.outputs.digest }}

